# Generated by Django 5.0.4 on 2024-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='img',
        ),
        migrations.AddField(
            model_name='skills',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
