# Generated by Django 5.0.4 on 2024-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_skills_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uservideo', models.FileField(upload_to='uservideos/')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterField(
            model_name='skills',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
