# Generated by Django 5.0.4 on 2024-05-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uservideo_delete_blogpost_alter_skills_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
