# Generated by Django 5.0.4 on 2024-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_skills_name_alter_skills_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='video',
            field=models.FileField(default=' ', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
