# Generated by Django 5.0.4 on 2024-05-09 13:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[accounts.models.validate_password_strength], verbose_name='password'),
        ),
    ]
